version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drip_dev
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
